MyGolfHandicapMVC/Controllers/ScoreCardsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using MyGolfHandicapMVC.Data;
using MyGolfHandicapCore.Models;

namespace MyGolfHandicapMVC.Controllers
{
    public class ScoreCardsController : Controller
    {
        private IClientAPI _clientAPI;

        public ScoreCardsController(IClientAPI clientAPI)
        {
            _clientAPI = clientAPI;
        }
        public async Task<IActionResult> Scorecards()
        {
            int UserId = HttpContext.Session.GetInt32("userid") ?? 0;

            if (UserId != 0)
            {
                var scorecards = await _clientAPI.GetScoreCardsAsync(UserId);
                ViewBag.ScoreCards = scorecards;
                ViewBag.menuHeader = "Scorecards";
                ViewBag.menu1Class = "unselected";
                ViewBag.menu2Class = "selected";
                ViewBag.menu3Class = "unselected";
                return View();
            }
            else 
            {
                return RedirectToAction("Logout", "Home");
            }
        }

        //[HttpGet("scorecards/addscorecard/{id}/{teeid}")]
        //[Route("api/scorecards/addscorecard/id/teeid")]
        public async Task<IActionResult> AddScoreCard(int id, int id2, int id3)
        {
            int courseid = id;
            int teeid = id2;
            int roundType = id3;
            GolfCourse course = null;
            Tee tee = null;
            IEnumerable<GolfCourse> golfCourses = await _clientAPI.GetGolfCoursesAsync();

            if (courseid == 0)
            {
                course = course = await _clientAPI.GetGolfCourseAsync(1); // Get default golf course
                tee = course.Tees.Where(t => t.TeeColour == "Yellow").FirstOrDefault();
            }
            else
            {
                course = await _clientAPI.GetGolfCourseAsync(courseid);

                if (teeid == 0)
                {
                    tee = course.Tees.Where(t => t.TeeColour == "Yellow").FirstOrDefault();

                    if (tee == null)
                    {
                        tee = course.Tees.FirstOrDefault();
                    }
                }
                else
                {
                    tee = course.Tees.Where(t => t.TeeId == teeid).FirstOrDefault();
                }
            }

            ViewBag.courseSelectList = new SelectList(golfCourses, "GolfCourseId", "Name", course.GolfCourseId);
            ViewBag.teeSelectList = new SelectList(course.Tees, "TeeId", "TeeColour", tee.TeeId);

            // round type 1 = 18, 2 = front 9, 3 = back 9
            switch (roundType)
            {
                case 1:
                    ViewBag.holeInfos = tee.Holes.OrderBy(h => h.HoleNumber).ToList();
                    ViewBag.roundType = 1;
                    ViewBag.score = tee.Holes.Sum(h => h.Par);
                    ViewBag.yards = tee.Holes.Sum(h => h.Yards);
                    break;
                case 2:
                    ViewBag.holeInfos = tee.Holes.Where(h => h.HoleNumber >= 1 && h.HoleNumber <= 9).OrderBy(h => h.HoleNumber).ToList();
                    ViewBag.roundType = 2;
                    ViewBag.score = tee.Holes.Where(h => h.HoleNumber >= 1 && h.HoleNumber <= 9).Sum(h => h.Par);
                    ViewBag.yards = tee.Holes.Where(h => h.HoleNumber >= 1 && h.HoleNumber <= 9).Sum(h => h.Yards);
                    break;
                case 3:
                    ViewBag.holeInfos = tee.Holes.Where(h => h.HoleNumber >= 10 && h.HoleNumber <= 18).OrderBy(h => h.HoleNumber).ToList();
                    ViewBag.roundType = 3;
                    ViewBag.score = tee.Holes.Where(h => h.HoleNumber >= 10 && h.HoleNumber <= 18).Sum(h => h.Par);
                    ViewBag.yards = tee.Holes.Where(h => h.HoleNumber >= 10 && h.HoleNumber <= 18).Sum(h => h.Yards);
                    break;
                default:
                    ViewBag.holeInfos = tee.Holes.OrderBy(h => h.HoleNumber).ToList();
                    ViewBag.roundType = 1;
                    ViewBag.score = tee.Holes.Sum(h => h.Par);
                    ViewBag.yards = tee.Holes.Sum(h => h.Yards);
                    break;
            }

            ViewBag.menuHeader = "Submit Scorecard";
            ViewBag.menu1Class = "unselected";
            ViewBag.menu2Class = "unselected";
            ViewBag.menu3Class = "selected";
            ViewBag.scorecard_id = 5;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddScoreCardSubmit(AddScoreCardForm scoreCard)
        {
            int UserId = HttpContext.Session.GetInt32("userid") ?? 0;

            if (UserId != 0)
            {
                scoreCard.user_id = UserId;
                await _clientAPI.AddScoreCardAsync(scoreCard);
                ViewBag.menuHeader = "Submit Scorecard";
                ViewBag.handicapIndex = await _clientAPI.GetHandicapIndexAsync(UserId);
                ViewBag.menu1Class = "unselected";
                ViewBag.menu2Class = "unselected";
                ViewBag.menu3Class = "selected";
                return View();
            }
            else
            {
                return RedirectToAction("Logout", "Home");
            }
        }

        [HttpPost]
        public async Task<IActionResult> UpdateScoreCard(int scorecardid)
        {
            ScoreCard scoreCard = await _clientAPI.GetScoreCardAsync(scorecardid);
            GolfCourse course = await _clientAPI.GetGolfCourseAsync(scoreCard.GolfCourseId);
            ViewBag.course = course;
            ViewBag.scoreCard = scoreCard;
            ViewBag.date = scoreCard.Date.ToString("dd'/'MM'/'yyyy");
            ViewBag.score = scoreCard.HoleScores.Sum(h => h.Score);
            ViewBag.yards = scoreCard.HoleScores.Sum(h => h.Yards);
            ViewBag.menuHeader = "Scorecard Details";
            ViewBag.menu1Class = "unselected";
            ViewBag.menu2Class = "unselected";
            ViewBag.menu3Class = "unselected";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateScoreCardSubmit(UpdateScoreCardForm scoreCard)
        {
            int UserId = HttpContext.Session.GetInt32("userid") ?? 0;

            if (UserId != 0)
            {
                scoreCard.user_id = UserId;
                await _clientAPI.UpdateScoreCardAsync(scoreCard);
                ViewBag.menuHeader = "Submit Scorecard";
                ViewBag.handicapIndex = await _clientAPI.GetHandicapIndexAsync(UserId);
                ViewBag.menu1Class = "unselected";
                ViewBag.menu2Class = "unselected";
                ViewBag.menu3Class = "unselected";
                return View();
            }
            else
            {
                return RedirectToAction("Logout", "Home");
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeleteScorecard(int scorecardid)
        {
            await _clientAPI.DeleteScoreCardAsync(scorecardid);
            return RedirectToAction("Scorecards", "Scorecards");
        }
    }
}

MyGolfHandicapMVC/Views/ScoreCards/AddScoreCard.cshtml
@{
    ViewData["Title"] = "Add Score Card";
}
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(function () {
        var dtToday = new Date();

        var month = dtToday.getMonth() + 1;
        var day = dtToday.getDate();
        var year = dtToday.getFullYear();

        if (month < 10)
            month = '0' + month.toString();
        if (day < 10)
            day = '0' + day.toString();

        var maxDate = year + '-' + month + '-' + day;
        $("#date").attr("max", maxDate);
        $("#date").attr("value", maxDate);
    });
    function onGolfCourseSelect() {
        var courseid = document.getElementById('course_select').value;
        //var url = "https://localhost:44393/ScoreCards/AddScoreCard/" + courseid;
        var url = '@Url.Action("AddScoreCard","ScoreCards", new { id = "js-id"})'.replace("js-id", encodeURIComponent(courseid));

        //var url = "https://mygolfhandicapapp.azurewebsites.net/ScoreCards/AddScoreCard/" + courseid;
        console.log(url);
            location.href = url;
        }
        function onTeeSelect() {
            var courseid = document.getElementById('course_select').value;
            var teeid = document.getElementById('tee_select').value;
            //var url = "https://localhost:44393/ScoreCards/AddScoreCard/" + courseid + "/" + teeid;
            //var url = "https://mygolfhandicapapp.azurewebsites.net/ScoreCards/AddScoreCard/" + courseid + "/" + teeid;
            var url = '@Url.Action("AddScoreCard","ScoreCards", new { id = "js-id", id2 = "js-id2"})'.replace("js-id", encodeURIComponent(courseid)).replace("js-id2", encodeURIComponent(teeid));
            console.log(url);
            location.href = url;
        }
        function onHoleSelect(roundType) {
            var courseid = document.getElementById('course_select').value;
            var teeid = document.getElementById('tee_select').value;
            //var url = "https://localhost:44393/ScoreCards/AddScoreCard/" + courseid + "/" + teeid + "/" + roundType;
            //var url = "https://mygolfhandicapapp.azurewebsites.net/ScoreCards/AddScoreCard/" + courseid + "/" + teeid + "/" + roundType;
            var url = '@Url.Action("AddScoreCard","ScoreCards", new { id = "js-id", id2 = "js-id2", id3 = "js-id3"})'.replace("js-id", encodeURIComponent(courseid)).replace("js-id2", encodeURIComponent(teeid)).replace("js-id3", encodeURIComponent(roundType));
            console.log(url);
            location.href = url;
        }
        function down(id) {
            var holeid = "hole" + id;
            var hidden_score = "hole_score_" + id;
            var score = document.getElementById(hidden_score).value;

            if (score > 1) {
                document.getElementById(holeid).innerHTML--;
                document.getElementById(hidden_score).value--;
                document.getElementById('score').innerHTML--;
            }
        }
        function up(id) {
            var holeid = "hole" + id;
            var hidden_score = "hole_score_" + id;
            document.getElementById(holeid).innerHTML++;
            document.getElementById(hidden_score).value++;
            document.getElementById('score').innerHTML++;
        }
</script>
<form asp-controller="ScoreCards" asp-action="AddScoreCardSubmit" method="post">
    <input type="hidden" id="scorecard_id" name="scorecard_id" value="@ViewBag.scorecard_id" />
    <div class="div_course_addscorecard">
        <span class="span_addscorecard">Course</span><select id="course_select" asp-items="@ViewBag.courseSelectList" onchange="onGolfCourseSelect()" name="golf_course_id" style="font-size:16px"></select>
        <span class="span_addscorecard">Tee</span><select id="tee_select" asp-items="@ViewBag.teeSelectList" onchange="onTeeSelect()" name="tee_id" style="font-size:16px"></select>
    </div>
    <div class="div_roundtype_addscorecard">
        <input type="radio" id="radio_18" value="1" name="round_type" onclick="onHoleSelect(1)" @(ViewBag.roundType == 1 ? "checked" : "")><label for="radio_18">18 Holes</label>
        <input type="radio" id="radio_front_9" value="2" name="round_type" onclick="onHoleSelect(2)" @(ViewBag.roundType == 2 ? "checked" : "")><label for="radio_9">Front 9</label>
        <input type="radio" id="radio_back_9" value="3" name="round_type" onclick="onHoleSelect(3)" @(ViewBag.roundType == 3 ? "checked" : "")><label for="radio_9">Back 9</label><br />
    </div>
    <div class="div_date_addscorecard">
        <span class="span_addscorecard">Date</span><input type="date" id="date" name="date" />
    </div>
    <div class="table_addscorecard">
        <table id="score_card">
            <tr>
                <th class="border">Hole</th>
                <th class="border">Yards</th>
                <th class="border">Par</th>
                <th class="border">SI</th>
                <th class="border">Score</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var hole in ViewBag.HoleInfos)
            {
                var holeid = "hole" + hole.HoleNumber;
                var hidden_score_name = "hole_score_" + hole.HoleNumber;
                <tr>
                    <td class="border">@hole.HoleNumber</td>
                    <td class="border">@hole.Yards</td>
                    <td class="border">@hole.Par</td>
                    <td class="border">@hole.StrokeIndex</td>
                    <td class="border score" id="@holeid">@hole.Par</td>
                    <td><input type="hidden" id="@hidden_score_name" name="@hidden_score_name" value="@hole.Par" /></td>
                    <td class="border"><i class="fa-solid fa-square-minus" style="font-size: 24px; color: #04bb66;" onclick="down(@hole.HoleNumber)"></i></td>
                    <td class="border"><i class="fa-solid fa-square-plus" style="font-size: 24px; color: #04bb66;" onclick="up(@hole.HoleNumber)"></i></td>
                </tr>
            }
            <tr>
                <td></td>
                <td>@ViewBag.yards</td>
                <td></td>
                <td></td>
                <td id="score">@ViewBag.score</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </table>
    </div>
    <div class="div_submit_addscorecard">
        <button type="submit" class="button_submit">Submit Scorecard</button>
    </div>
</form>

MyGolfHandicapMVC/Views/ScoreCards/AddScoreCardSubmit.cshtml
@{
    //Layout = null;
}
<h2 class="header_center">Success</h2>
<h2 class="header_center">Your updated handicap index is @ViewBag.handicapIndex</h2>
<div class="div_submit_addscorecard">
    <form asp-controller="scorecards" asp-action="addscorecard" method="get">
        <button type="submit" class="button_submit_another">Submit Another Scorecard</button>
    </form>
</div>

MyGolfHandicapMVC/Views/ScoreCards/Scorecards.cshtml
@{
    //Layout = null;
}
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
<script src="~/js/site.js" asp-append-version="true"></script>
<div class="table_scorecards">
    <table>
        <tr>
            <th>Golf Course</th>
            <th>Date</th>
            <th>Tee</th>
            <th>Holes Played</th>
            <th>Total</th>
            <th>Score</th>
            <th></th>
        </tr>
        @foreach (var scorecard in ViewBag.ScoreCards)
        {
    <tr>
        <td>@scorecard.CourseName</td>
        <td>@scorecard.Date.ToString("dd'/'MM'/'yy")</td>
        <td>@scorecard.TeeColour</td>
        <td>@scorecard.HolesPlayed</td>
        <td>@scorecard.GrossScore</td>
        <td>@scorecard.Score</td>
        <td>
            <form method="post" asp-controller="ScoreCards" asp-action="UpdateScoreCard" class="form_delete">
                <input type="hidden" name="scorecardid" value="@scorecard.ScoreCardId" />
                <button type="submit" class="button_delete"><span class="icon_delete"><i class="fa fa-pen fa-soild"></i></span></button>
            </form>
        </td>
        <td>
            <form method="post" asp-controller="ScoreCards" asp-action="DeleteScoreCard" class="form_delete">
                <input type="hidden" name="scorecardid" value="@scorecard.ScoreCardId" />
                <button type="submit" class="button_delete"><span class="icon_delete"><i class="fa fa-trash"></i></span></button>
            </form>
        </td>
    </tr>
        }
    </table>
</div>

MyGolfHandicapMVC/Views/ScoreCards/UpdateScoreCard.cshtml
@{
    ViewData["Title"] = "Add Score Card";
}
<link rel="stylesheet" href="~/css/site.css" />
<link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
<script>
    function down(id) {
        var holeid = "hole" + id;
        var hidden_score = "hole_score_" + id;
        var score = document.getElementById(hidden_score).value;

        if (score > 1) {
            document.getElementById(holeid).innerHTML--;
            document.getElementById(hidden_score).value--;
            document.getElementById('score').innerHTML--;
        }
    }
    function up(id) {
        var holeid = "hole" + id;
        var hidden_score = "hole_score_" + id;
        document.getElementById(holeid).innerHTML++;
        document.getElementById(hidden_score).value++;
        document.getElementById('score').innerHTML++;
    }
</script>
<div class="div_scorecard_details">
    <table class="table_scorecard_details">
        <tr>
            <td style="font-weight:bold">Golf Course</td>
            <td>@ViewBag.course.Name</td>
        </tr>
        <tr>
            <td style="font-weight:bold">Tee</td>
            <td>@ViewBag.scoreCard.TeeColour</td>
        </tr>
        <tr>
            <td style="font-weight:bold">Date</td>
            <td>@ViewBag.date</td>
        </tr>
        <tr>
            <td style="font-weight:bold">Holes Played</td>
            <td>@ViewBag.scoreCard.GetHolesPlayed()</td>
        </tr>
    </table>
</div>
<form asp-controller="ScoreCards" asp-action="UpdateScoreCardSubmit" method="post">
    <input type="hidden" id="scorecard_id" name="scorecard_id" value="@ViewBag.scoreCard.ScoreCardId" />
    <div class="table_addscorecard">
        <table id="score_card" style="margin-top:30px">
            <tr>
                <th class="border">Hole</th>
                <th class="border">Yards</th>
                <th class="border">Par</th>
                <th class="border">SI</th>
                <th class="border">Score</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var hole in ViewBag.scorecard.HoleScores)
            {
                var holeid = "hole" + hole.HoleNumber;
                var hidden_score_name = "hole_score_" + hole.HoleNumber;
                <tr>
                    <td class="border">@hole.HoleNumber</td>
                    <td class="border">@hole.Yards</td>
                    <td class="border">@hole.HolePar</td>
                    <td class="border">@hole.StrokeIndex</td>
                    <td class="border score" id="@holeid">@hole.Score</td>
                    <td><input type="hidden" id="@hidden_score_name" name="@hidden_score_name" value="@hole.Score" /></td>
                    <td class="border"><i class="fa-solid fa-square-minus" style="font-size: 24px; color: #04bb66;" onclick="down(@hole.HoleNumber)"></i></td>
                    <td class="border"><i class="fa-solid fa-square-plus" style="font-size: 24px; color: #04bb66;" onclick="up(@hole.HoleNumber)"></i></td>
                </tr>
            }
            <tr>
                <td></td>
                <td>@ViewBag.yards</td>
                <td></td>
                <td></td>
                <td id="score">@ViewBag.score</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </table>
    </div>
    <div class="div_submit_addscorecard">
        <button type="submit" class="button_submit">Update Scorecard</button>
    </div>
</form>

MyGolfHandicapMVC/Views/ScoreCards/UpdateScoreCardSubmit.cshtml
@{
}
<h2 class="header_center">Update Success</h2>
<h2 class="header_center">Your updated handicap index is @ViewBag.handicapIndex</h2>